### ISSUE TITLE
Picture file can't be found during pdf compilation

### ISSUE THREAD

**Issue by blacksqr** [davidcarayon/quarto-inrae-extension#5]
I added your extension to my project directory, and rendered via command line: `quarto render --to inrae-pdf`

I got the following error:

```
compilation failed- error
Unable to load picture or PDF file '_extensions/inrae/ressources/photo.png'.
```

Should the file path be relative to the .tex file in the `/ressources` directory rather than to the quarto project directory?  Sorry, I'm a latex beginner.  I'm using Linux.

output file index.log attached below.

Full quarto output:

```
pandoc 
  to: latex
  output-file: index.tex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  crossref:
    chapters: true
  documentclass: scrreprt
  papersize: letter
  classoption:
    - DIV=11
    - numbers=noendperiod
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  sansfont: Raleway
  mainfont: Avenir Next LT Pro
  toc-title: Sommaire
  geometry:
    - top=25mm
    - left=25mm
    - right=25mm
    - bottom=25mm
  bibliography:
    - Mybook.bib
  title: 'My Book'
  date: 4/21/2023
  author: Me
  description: 'My Book description'
  
running xelatex - 1
  This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Unable to load picture or PDF file '_extensions/inrae/ressources/photo.png'.
<to be read again> 
                   }
l.204 ..._extensions/inrae/ressources/photo.png}}}
                                                  % 
```

[index.log](https://github.com/davidcarayon/quarto-inrae-extension/files/11557834/index.log)
